sudo: false
language: ruby
cache: bundler

rvm:
  - 2.1.10
  - 2.3.1

env:
  - GRAPHQL_VERSION=0.18.0 RAILS_VERSION=3.0.0
  - GRAPHQL_VERSION=0.18.0 RAILS_VERSION=5.0.0
  - GRAPHQL_VERSION=0.18.11 RAILS_VERSION=3.0.0
  - GRAPHQL_VERSION=0.18.11 RAILS_VERSION=5.0.0
