sudo: false
language: ruby
cache: bundler

rvm:
  - 2.1.10
  - 2.2.9
  - 2.3.5
  - 2.4.3
  - 2.5.0

env:
  - GRAPHQL_VERSION=1.6.6 RAILS_VERSION=3.2.22
  - GRAPHQL_VERSION=1.6.6 RAILS_VERSION=5.0.5
  - GRAPHQL_VERSION=1.6.6 RAILS_VERSION=3.2.22
  - GRAPHQL_VERSION=1.6.6 RAILS_VERSION=5.0.5
  - GRAPHQL_VERSION=1.8-dev RAILS_VERSION=5.0.5

matrix:
  exclude:
  - rvm: 2.1.10
    env: GRAPHQL_VERSION=1.6.6 RAILS_VERSION=5.0.5
  - rvm: 2.1.10
    env: GRAPHQL_VERSION=1.6.6 RAILS_VERSION=5.0.5
  - rvm: 2.1.10
    env: GRAPHQL_VERSION=1.8-dev RAILS_VERSION=5.0.5
