sudo: false
language: ruby
cache: bundler

rvm:
  - 2.5.6
  - 2.6.4

env:
  - RAILS_VERSION=5.2.0 GRAPHQL_VERSION=1.8.11
  - RAILS_VERSION=5.2.0 GRAPHQL_VERSION=1.9.12
  - RAILS_VERSION=edge GRAPHQL_VERSION=edge

matrix:
  exclude:
  - rvm: 2.4.4
    env: RAILS_VERSION=edge
  - rvm: 2.3.7
    env: RAILS_VERSION=edge
